# Site settings
title: Scully.ðŸ¶
email: info@scully.dog
description: > # this means to ignore newlines until "baseurl:"
  Documenting the journey of the worlds cutest dog "Scully". She''s a skeptic!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
github_username:  mulchy

# Build settings
markdown: kramdown

exclude: [vendor]
